version: '3.8'

services:
  app:
    image: localhost/langchain-chatglm:latest
    container_name: chat
    ports:
      - "7733:7860"
    volumes:
      - ./:/chatGLM/
    environment:
      - GPT35_KEY_FILE=/run/secrets/chat-gpt35-api-key
      - CALL_AZURE_OPENAI=True
      - AZURE_OPENAI_ENDPOINT_FILE='https://sandbox-openai-east-us.openai.azure.com'
      - AZURE_OPENAI_KEY_FILE=/run/secrets/chat-azure-gpt-api-key
      - AZURE_OPENAI_VERSION_FILE=/run/secrets/chat-azure-gpt-version
      - AZURE_OPENAI_ENGINE_FILE=/run/secrets/chat-azure-gpt-engine
    secrets:
      - chat-azure-gpt-version
      - chat-azure-gpt-engine
      - chat-azure-gpt-api-key
      - chat-gpt35-api-key
    # command: python -u webui.py
    # command: python -u api.py
    command: tail -F /dev/null

  chat-view:
    build:
      context: .
      dockerfile: views/Dockerfile
    # image: localhost/chat-view:latest
    container_name: chatview
    ports:
      - "8080:80"
      - "8043:443"
    volumes:
      - ./views/docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

secrets:
   chat-azure-gpt-version:
     external: true
   chat-azure-gpt-engine:
     external: true
   chat-azure-gpt-api-key:
     external: true
   chat-gpt35-api-key:
     external: true
